# -*- coding: utf-8 -*-
"""KNN-실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRyYdh6m-gGlp4c3OBfrrDx5cDuJKKgK
"""

# Sklearn 에서 지원해주는 학습 데이터인 Iris 데이터를 dataset에서 불러와 근접 이웃 값인 K를 변화 시켜 가면서 어떤 k 값이 최적의 값인지 찾고 그 정확도를 출력해 보자.

import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# iris 데이터를 읽어온다
iris = load_iris()

# 8:2 비율로 학습 데이터와 시험 데이터를 분리한다.
n = int(iris['data'].shape[0] * 0.8)

# x_train = iris['data'][:n]
# y_train = iris['target'][:n]
# x_test = iris['data'][n:]
# y_test = iris['target'][n:]
# 위와 같은 방법도 가능하다.

# train, test 분리

x_train, x_test, y_train, y_test = train_test_split(iris['data'], iris['target'], test_size=0.2)
# 셔플 해주기 때문에 실행시 마다 결과가 다르게 나온다.
# 문제점 중에 하나인 같은 target 값을 가지는 feature 들이 모여 있을 경우 해당 값이 근접할 가능성이 높아진다
# 이를 해결하기 위해서 값을 한번 섞어서 근접 값을 찾아줘야 한다.

# k를 변화시켜가면서 정확도를 측정해 본다
acc_test = []
acc_train = []
k_max = 30
for k in range(1, k_max):
    # KNN 으로 학습 데이터 세트를 학습한다.
    knn = KNeighborsClassifier(n_neighbors=k, p=2, weights='uniform')
    knn.fit(x_train, y_train)
    
    # 시험 데이터의 Feature에 대한 정확도
    y_pred = knn.predict(x_test)
    acc_test.append((y_test == y_pred).mean())
    # acc_test.append(knn.score(x_test, y_test))
    
    # 학습 데이터의 Feature에 대한 정확도
    y_pred = knn.predict(x_train)
    acc_train.append((y_train == y_pred).mean())
    # acc_train.append(knn.score(x_train, y_train))

    # 아래처럼해도 된다.
    # acc_test.append(knn.score(x_test, y_test))
    # acc_train.append(knn.score(x_train, y_train))

# k의 값에 따라 변화는 정확도를 표로 표현해 본다.

plt.figure(figsize=(8, 5))
plt.plot(acc_test, marker='o', label="Test Data")
plt.plot(acc_train, marker='o', label="Train Data")
plt.legend()
plt.xlabel("k")
plt.ylabel("Accuracy")
plt.xticks(np.arange(k_max), np.arange(1, k_max + 1))
plt.show()

# 정확도를 측정한다.
# test 데이터의 target값을 가장 잘 맞췄던 k값을 최적(optimal)값으로 정하고 해당 정확도를 출력해준다.

opt_k = np.argmax(acc_test)
opt_acc = acc_test[opt_k]

print("optimal k = {}, accuracy = {:.3f}".format(opt_k + 1, opt_acc))

